sources:
  - title: "Probability and Statistics for Engineers and Scientists"
    author: "Ronald E. Walpole, Raymond H. Myers, Sharon L. Myers, and Keying E. Ye"
    type: book
    isbn: "978-0-321-62911-1"
    section: "9th Edition"
    published: "2011"
