FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server/ ./server/

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--reload", "--access-logfile", "-", "--chdir", "/app/server", "app:app"]
