FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY api/ ./api/

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--reload", "app:app"]
