services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8081:80"
    container_name: mathnotes-test
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s