sources:
  - title: "Measure, Integration & Real Analysis"
    author: "Sheldon Axler"
    type: book
    isbn: "978-3-030-33142-9"
    publisher: "Springer"
    published: "2020"
    url: "https://measure.axler.net/"
