sources:
  - title: "Numerical Analysis"
    author: "Richard L. Burden, J. Douglas Faires, and Annette M. Burden"
    type: book
    isbn: "978-1-305-25366-7"
    section: "10th Edition"
    published: "2015"
