sources:
  - title: "Introduction to Partial Differential Equations"
    author: "Peter J. Olver"
    type: book
    isbn: "978-3-319-02098-3"
    section: "Undergraduate Texts in Mathematics"
    published: "2014"
