sources:
  - title: "Nonlinear Dynamics and Chaos"
    author: "Steven H. Strogatz"
    type: book
    isbn: "978-1032665214"
    section: "3rd Edition"
    publisher: "Chapman and Hall/CRC"
    published: "2024"
